{
  inputs,
  self,
  withSystem,
  ...
}:
{
  flake = {
    nixosConfigurations.Goofeus = withSystem "x86_64-linux" (
      { config, inputs', ... }:
      inputs.nixpkgs.lib.nixosSystem {
        specialArgs = {
          inherit inputs inputs';
          inherit (config) packages;
          username = "root";
          inherit (config.legacyPackages) pkgs-stable pkgs-for-cursor pkgs-for-homelab;
          hostname = self.constants.serverName;
        };
        modules = with self.nixosModules; [
          Goofeus
          GoofeusHardware
          self.stylixCommon
          inputs.home-manager.nixosModules.home-manager
          inputs.stylix.nixosModules.stylix
          inputs.agenix.nixosModules.default
          self.nixpkgsConfig
          self.nixConfig
          tailscale
          glance
          arr
          immich
          copyparty
          donetick
          # nextcloud
          caddy
          # coredns
        ];
      }
    );

    homeConfigurations.Goofeus = {
      imports = with self.homeModules; [
        nixos-home
        atuin
        zoxide
        nushell
        neovim
        starship
        yazi
        git
        delta
        gh
        direnv
        lazygit
        btop
        bat
        nix-index-database
      ];
    };

    nixosModules.Goofeus =
      {
        pkgs,
        pkgs-stable,
        username,
        hostname,
        pkgs-for-cursor,
        ...
      }:
      {
        home-manager = {
          useGlobalPkgs = true;
          useUserPackages = true;
          extraSpecialArgs = {
            inherit
              hostname
              username
              pkgs-for-cursor
              pkgs-stable
              ;
          };
          backupFileExtension = "hm-backup-1";
        };
        # Use the systemd-boot EFI boot loader.
        boot.loader.systemd-boot.enable = true;
        boot.loader.efi.canTouchEfiVariables = true;

        networking.hostName = hostname;
        networking.firewall.enable = true;

        # Configure network connections interactively with nmcli or nmtui.
        networking.networkmanager.enable = true;

        environment.sessionVariables =
          let
            homeDir = if username == "root" then "/root" else "/home/${username}";
          in
          {
            NH_OS_FLAKE = "${homeDir}/NixConfig";
          };
        environment.shells = with pkgs; [
          nushell
          bash
        ];

        # Set your time zone.
        time.timeZone = "Asia/Hong_Kong";

        # Select internationalisation properties.
        i18n.defaultLocale = "en_HK.UTF-8";

        security.sudo = {
          enable = true;
          wheelNeedsPassword = false;
        };

        environment.systemPackages = with pkgs; [
          fzf
          ripgrep
          zip
          unzip
          nh
          nvd
          nix-output-monitor
          dua
          lazyjournal
          btop
          powertop
          lazydocker
          systemctl-tui
        ];

        # Define a user account. Don't forget to set a password with ‘passwd’.
        users.users.${username} = {
          shell = pkgs.nushell;
          openssh.authorizedKeys.keys = with self.sshKeys; [
            GoofyDesky
            GoofyEnvy
            Droid
          ];
        };

        # Enable the OpenSSH daemon.
        services.openssh.enable = true;

        home-manager.users.${username} = self.homeConfigurations.Goofeus;

        swapDevices = [
          {
            device = "/swapfile";
            size = 4 * 1024;
          }
        ];
        powerManagement.powertop.enable = true;

        virtualisation.docker.enable = true;

        system.stateVersion = "26.05";
      };

    # Do not modify this module!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    nixosModules.GoofeusHardware =
      {
        config,
        lib,
        modulesPath,
        ...
      }:
      {
        imports = [
          (modulesPath + "/installer/scan/not-detected.nix")
        ];

        boot.initrd.availableKernelModules = [
          "xhci_pci"
          "ahci"
          "usbhid"
          "usb_storage"
          "sd_mod"
        ];
        boot.initrd.kernelModules = [ ];
        boot.kernelModules = [ "kvm-intel" ];
        boot.extraModulePackages = [ ];

        fileSystems."/" = {
          device = "/dev/disk/by-label/NIXROOT";
          fsType = "ext4";
        };

        fileSystems."/boot" = {
          device = "/dev/disk/by-label/NIXBOOT";
          fsType = "vfat";
          options = [
            "fmask=0022"
            "dmask=0022"
          ];
        };

        fileSystems."/mnt/2TBSeagateHDD" = {
          device = "/dev/disk/by-label/2TBSeagateHDD";
          fsType = "ext4";
          options = [
            "defaults"
            "users"
            "nofail"
          ];
        };

        nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
        hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };

  };
}
